version: '3.8'

services:
  telegram_bot:
    ports:
      - 8443:8443
    build:
      context: .
      dockerfile: bot_service/Dockerfile
    volumes:
      - .:/app
    #depends_on:
    #  - db
    #  - redis
    #environment:
    #  - PYTHONUNBUFFERED=1

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/hackathon-undefined.ru/fullchain.pem:/etc/letsencrypt/live/hackathon-undefined.ru/fullchain.pem
      - /etc/letsencrypt/live/hackathon-undefined.ru/privkey.pem:/etc/letsencrypt/live/hackathon-undefined.ru/privkey.pem

  redis:
    image: redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly no --notify-keyspace-events Ex
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - 6379:6379
    networks:
      - web
    
  postgres:
    image: postgres:latest
    volumes:
      - postgres_stat:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - web

networks:
  web:
    external: true