version: '3.8'

services:
  telegram_bot:
    ports:
      - 8443:8443
    build:
      context: .
      dockerfile: bot_service/Dockerfile
    volumes:
      - .:/app
    #depends_on:
    #  - db
    #  - redis
    #environment:
    #  - PYTHONUNBUFFERED=1

networks:
  web:
    external: true