version: '3.8'

services:
  telegram_bot:
    ports:
      - 8443:8443
    build:
      context: .
      dockerfile: bot_service/Dockerfile
    volumes:
      - .:/app
    #depends_on:
    #  - db
    #  - redis
    #environment:
    #  - PYTHONUNBUFFERED=1

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/hackathon-undefined.ru/fullchain.pem:/etc/letsencrypt/live/hackathon-undefined.ru/fullchain.pem
      - /etc/letsencrypt/live/hackathon-undefined.ru/privkey.pem:/etc/letsencrypt/live/hackathon-undefined.ru/privkey.pem


networks:
  web:
    external: true